"""change user model

Revision ID: 098f75ee6a4c
Revises: 9ed61f565b43
Create Date: 2024-03-03 21:43:09.890878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "098f75ee6a4c"
down_revision: Union[str, None] = "9ed61f565b43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("contacts_created_by_fkey", "contacts", type_="foreignkey")
    op.create_foreign_key(
        None, "contacts", "users", ["created_by"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "contacts_channels_created_by_fkey", "contacts_channels", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "contacts_channels", "users", ["created_by"], ["id"], ondelete="CASCADE"
    )
    op.add_column("users", sa.Column("first_name", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("confirmed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "confirmed")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_constraint(None, "contacts_channels", type_="foreignkey")
    op.create_foreign_key(
        "contacts_channels_created_by_fkey",
        "contacts_channels",
        "users",
        ["created_by"],
        ["id"],
    )
    op.drop_constraint(None, "contacts", type_="foreignkey")
    op.create_foreign_key(
        "contacts_created_by_fkey", "contacts", "users", ["created_by"], ["id"]
    )
    # ### end Alembic commands ###
