"""change user model

Revision ID: 9ed61f565b43
Revises: 
Create Date: 2024-02-25 14:10:33.306826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9ed61f565b43"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("created_by", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "contacts", "users", ["created_by"], ["id"])
    op.add_column(
        "contacts_channels", sa.Column("created_by", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "contacts_channels", "users", ["created_by"], ["id"])
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.alter_column(
        "users",
        "refresh_token",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=1255),
        existing_nullable=True,
    )
    op.drop_column("users", "crated_at")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "username", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "crated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.alter_column(
        "users",
        "refresh_token",
        existing_type=sa.String(length=1255),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("users", "created_at")
    op.drop_constraint(None, "contacts_channels", type_="foreignkey")
    op.drop_column("contacts_channels", "created_by")
    op.drop_constraint(None, "contacts", type_="foreignkey")
    op.drop_column("contacts", "created_by")
    # ### end Alembic commands ###
